# Generated by Django 4.1.3 on 2022-12-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='league',
            new_name='league_name',
        ),
    ]
