# Generated by Django 4.1.3 on 2022-12-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_league_league_league_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='stadium_id',
            field=models.IntegerField(null=True),
        ),
    ]
