# Generated by Django 4.1.3 on 2022-12-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_player_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draftkings_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='draftkings_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fanduel_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fanduel_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fantasy_alarm_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fantasy_draft_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fantasy_draft_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fantasy_position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='roto_wire_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='roto_world_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sport_radar_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sports_direct_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='stats_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='usa_today_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='xml_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='yahoo_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='yahoo_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
