# Generated by Django 4.1.3 on 2022-12-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_player_age_alter_player_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('betting_event_type_id', models.IntegerField()),
                ('betting_event_type_name', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BettingMarketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('betting_market_type_id', models.IntegerField()),
                ('betting_market_type_name', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BettingOutcomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('betting_outcome_type_id', models.IntegerField()),
                ('betting_outcome_type_name', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BettingPeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('betting_period_type_id', models.IntegerField()),
                ('betting_period_type_name', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BettingResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('betting_result_type_id', models.IntegerField()),
                ('betting_result_type_name', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('bet_type_id', models.IntegerField()),
                ('bet_type_name', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sportsbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_sportsbook_id', models.IntegerField()),
                ('sportsbook_name', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultedMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('last_updated_utc', models.DateTimeField()),
                ('bet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.bettype')),
                ('betting_market_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.bettingmarkettype')),
                ('betting_period_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.bettingperiodtype')),
            ],
        ),
    ]
