# Generated by Django 4.1.3 on 2022-12-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_bettingeventtype_bettingmarkettype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betting_event_id', models.IntegerField()),
                ('betting_event_name', models.CharField(max_length=100)),
                ('betting_event_season', models.IntegerField()),
                ('betting_event_type_id', models.IntegerField()),
                ('betting_event_type_name', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField()),
                ('score_id', models.IntegerField(null=True)),
                ('global_score_id', models.IntegerField(null=True)),
                ('game_status', models.CharField(max_length=100, null=True)),
                ('quarter', models.IntegerField(null=True)),
                ('away_team_score', models.IntegerField(null=True)),
                ('home_team_score', models.IntegerField(null=True)),
                ('total_score', models.IntegerField(null=True)),
                ('game_start_datetime', models.DateTimeField(null=True)),
                ('last_updated_utc', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_event_away_team', to='backend.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_event_home_team', to='backend.team')),
            ],
        ),
    ]
