# Generated by Django 4.1.3 on 2022-12-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_bettingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettingevent',
            name='quarter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
