# Generated by Django 4.1.3 on 2022-12-15 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_bettingmarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingevent',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_events', to='backend.league'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bettingevent',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_events', to='backend.sport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bettingmarket',
            name='betting_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_markets', to='backend.bettingevent'),
        ),
    ]
