# Generated by Django 4.1.3 on 2022-12-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_bettingevent_league_bettingevent_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettingevent',
            name='league',
        ),
        migrations.RemoveField(
            model_name='bettingevent',
            name='sport',
        ),
    ]
