# Generated by Django 4.1.3 on 2022-12-15 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_bettingmarket_league_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettingevent',
            name='league',
        ),
        migrations.RemoveField(
            model_name='bettingevent',
            name='sport',
        ),
        migrations.AddField(
            model_name='bettingmarket',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='betting_markets', to='backend.league'),
        ),
        migrations.AddField(
            model_name='bettingmarket',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='betting_markets', to='backend.sport'),
        ),
    ]
