# Generated by Django 4.1.3 on 2022-12-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_bettingmarket_last_updated_utc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(default='sportsdata', max_length=100)),
                ('betting_outcome_id', models.IntegerField()),
                ('betting_outcome_name', models.CharField(max_length=100)),
                ('participant', models.CharField(max_length=100)),
                ('is_available', models.BooleanField()),
                ('is_alternate', models.BooleanField()),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField()),
                ('unlisted_datetime', models.DateTimeField()),
                ('is_in_play', models.BooleanField()),
                ('sportsbook_url', models.CharField(max_length=500, null=True)),
                ('sportsbook_market_id', models.CharField(max_length=100, null=True)),
                ('sportsbook_outcome_id', models.CharField(max_length=100, null=True)),
                ('last_updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='bettingmarket',
            old_name='bets_available',
            new_name='is_bet_available',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='bettingevent',
            name='data_provider',
            field=models.CharField(default='sportsdata', max_length=100),
        ),
        migrations.AddField(
            model_name='bettingmarket',
            name='data_provider',
            field=models.CharField(default='sportsdata', max_length=100),
        ),
        migrations.CreateModel(
            name='BettingOutcomePriceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('payout_american', models.IntegerField()),
                ('payout_decimal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_first_update', models.BooleanField()),
                ('is_most_recent_update', models.BooleanField()),
                ('update_datetime_utc', models.DateTimeField()),
                ('betting_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcome_updates', to='backend.bettingoutcome')),
                ('previous_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.bettingoutcomepriceupdate')),
            ],
        ),
        migrations.AddField(
            model_name='bettingoutcome',
            name='betting_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcomes', to='backend.bettingmarket'),
        ),
        migrations.AddField(
            model_name='bettingoutcome',
            name='betting_outcome_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcomes', to='backend.bettingoutcometype'),
        ),
        migrations.AddField(
            model_name='bettingoutcome',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcomes', to='backend.league'),
        ),
        migrations.AddField(
            model_name='bettingoutcome',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcomes', to='backend.player'),
        ),
        migrations.AddField(
            model_name='bettingoutcome',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcomes', to='backend.sport'),
        ),
        migrations.AddField(
            model_name='bettingoutcome',
            name='sportsbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcomes', to='backend.sportsbook'),
        ),
        migrations.AddField(
            model_name='bettingoutcome',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='betting_outcomes', to='backend.team'),
        ),
    ]
