# Generated by Django 4.1.3 on 2022-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_bettingoutcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettingoutcome',
            name='participant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bettingoutcome',
            name='unlisted_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bettingoutcome',
            name='updated_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
