# Generated by Django 4.1.3 on 2022-12-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_bettingoutcome_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettingoutcome',
            name='betting_outcome_name',
        ),
    ]
