# Generated by Django 4.1.3 on 2022-12-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_bettingoutcome_betting_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettingevent',
            name='betting_event_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bettingmarket',
            name='betting_market_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bettingoutcome',
            name='betting_outcome_id',
            field=models.IntegerField(unique=True),
        ),
    ]
