# Generated by Django 4.1.3 on 2022-12-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_bettingevent_betting_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingMarketOutcomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_outcome_type_combo', models.CharField(max_length=200)),
                ('betting_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_market_outcome_types', to='backend.bettingmarket')),
                ('betting_outcome_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betting_market_outcome_types', to='backend.bettingoutcometype')),
            ],
        ),
    ]
