# Generated by Django 4.1.3 on 2023-01-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_bet_betpriceupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='backend.bet'),
        ),
    ]
