# Generated by Django 4.1.3 on 2023-01-20 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('payout_american', models.IntegerField()),
                ('placed_datetime', models.DateTimeField()),
                ('result', models.CharField(max_length=50, null=True)),
                ('result_update_datetime', models.DateTimeField(null=True)),
                ('betting_market_outcome_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets_placed', to='backend.bettingmarketoutcometype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets_placed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
