# Generated by Django 4.1.3 on 2023-01-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_user_account_balance_userbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='wager_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
