# Generated by Django 4.1.3 on 2023-02-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_remove_userbet_result_betpriceupdate_betting_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='betting_price_updates',
            field=models.ManyToManyField(related_name='bets_placed', to='backend.betpriceupdate'),
        ),
    ]
