# Generated by Django 4.1.3 on 2023-02-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_rename_betting_price_updates_userbet_bet_price_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettingmarketoutcometype',
            name='market_outcome_type_combo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
