# Generated by Django 4.1.3 on 2023-02-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_bettingmarketoutcometype_market_outcome_type_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='backend.bettingmarketoutcometype'),
        ),
    ]
